
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1.02 EDK_I.20.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	},
	{
		XPAR_LED_7SEGMENT_DEVICE_ID,
		XPAR_LED_7SEGMENT_BASEADDR,
		XPAR_LED_7SEGMENT_INTERRUPT_PRESENT,
		XPAR_LED_7SEGMENT_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_3BIT_DEVICE_ID,
		XPAR_PUSH_BUTTONS_3BIT_BASEADDR,
		XPAR_PUSH_BUTTONS_3BIT_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_3BIT_IS_DUAL
	},
	{
		XPAR_DIP_SWITCHES_8BIT_DEVICE_ID,
		XPAR_DIP_SWITCHES_8BIT_BASEADDR,
		XPAR_DIP_SWITCHES_8BIT_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_8BIT_IS_DUAL
	}
};


