#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/ensiens.imag.fr/moy/sle-tlm/TPs/corrige/tp3/fpga/system.xmp
#################################################################

XILINX_EDK_DIR = /Xilinx/8.1i/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = spartan3

DEVICE = xc3s1000ft256-4

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp pcores/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) \
                   $(MICROBLAZE_0_LIBG_OPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

SOFTWARE_OUTPUT_DIR = software
SOFTWARE_OUTPUT = $(SOFTWARE_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(SOFTWARE_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(SOFTWARE_OUTPUT) 

ALL_USER_ELF_FILES = $(SOFTWARE_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM).do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM).do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM).do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       microblaze_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = 

CORE_STATE_DEVELOPMENT_FILES = /Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/proc_common_pkg.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/direct_path_cntr.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/srl_fifo.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/srl_fifo_rbu.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/pselect.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/ld_arith_reg.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/ld_arith_reg2.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/down_counter.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/inferred_lut4.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/or_muxcy.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/or_gate.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v1_00_b/hdl/vhdl/family.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/ipif_pkg.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/interrupt_control.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/ipif_steer.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/dma_sg_pkg.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/dma_sg_cmp.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/ctrl_reg.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/burst_size_calc.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/dma_sg.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/ipif_common_v1_00_d/hdl/vhdl/dma_sg_sim.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/address_decoder.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/slave_attachment.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_counter_bit.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_counter.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_counter_top.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_occ_counter.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_occ_counter_top.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_adder_bit.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_adder.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_dpram_select.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/srl16_fifo.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/pf_dly1_mux.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/rdpfifo_dp_cntl.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ipif_control_rd.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/rdpfifo_top.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/wrpfifo_dp_cntl.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ipif_control_wr.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/wrpfifo_top.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/bus2ip_amux.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ip2bus_dmux.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ip2bus_dmux_blk.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ip2bus_srmux.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ip2bus_srmux_blk.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/ipif_reset.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/reset_control.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/addr_load_and_incr.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/master_attachment.vhd \
/Xilinx/8.1i/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v2_00_h/hdl/vhdl/opb_ipif.vhd \
/home/ensiens.imag.fr/moy/sle-tlm/TPs/corrige/tp3/fpga/pcores/opb_vga_v1_00_a/hdl/vhdl/opb_vga.vhd

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/mb_opb_wrapper.ngc \
implementation/rs232_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc \
implementation/led_7segment_wrapper.ngc \
implementation/push_buttons_3bit_wrapper.ngc \
implementation/dip_switches_8bit_wrapper.ngc \
implementation/sram_256kx32_wrapper.ngc \
implementation/opb_intc_0_wrapper.ngc \
implementation/sram_256kx32_util_bus_split_0_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/opb_timer_0_wrapper.ngc \
implementation/opb_vga_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION SOFTWARE
#################################################################
# No C-sources specified 
